// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace MetroMania.Engine.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PassengerPickupAndDeliveryFeature : object, global::Xunit.IClassFixture<PassengerPickupAndDeliveryFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Passenger Pickup and Delivery", @"    Trains at stations pick up passengers they can deliver and drop off passengers
    whose destination matches the station type. Each passenger action takes 1 hour.
    The train stays at the station (dwells) for the total number of actions.
    Score increases by 1 for each passenger delivered.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PassengerDelivery.feature"
#line hidden
        
        public PassengerPickupAndDeliveryFeature(PassengerPickupAndDeliveryFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/PassengerDelivery.feature.ndjson", 20);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Train delivers a passenger and increases the score")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Train delivers a passenger and increases the score")]
        public async global::System.Threading.Tasks.Task TrainDeliversAPassengerAndIncreasesTheScore()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Train delivers a passenger and increases the score", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 24 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
        await testRunner.AndAsync("a level with a Triangle station at (1,0) with a spawn delay of 0 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
        await testRunner.AndAsync("the player will create a line connecting stations at (0,0) and (1,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
        await testRunner.AndAsync("the player will then add a vehicle to the created line at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
        await testRunner.WhenAsync("the simulation runs for 48 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
        await testRunner.ThenAsync("the total score should be greater than 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Train picks up a passenger at a station and carries it")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Train picks up a passenger at a station and carries it")]
        public async global::System.Threading.Tasks.Task TrainPicksUpAPassengerAtAStationAndCarriesIt()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Train picks up a passenger at a station and carries it", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 1 hour", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
        await testRunner.AndAsync("a level with a Triangle station at (3,0) with a spawn delay of 0 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
        await testRunner.AndAsync("the player will create a line connecting stations at (0,0) and (3,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
        await testRunner.AndAsync("the player will then add a vehicle to the created line at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
        await testRunner.WhenAsync("the simulation runs for 5 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
        await testRunner.ThenAsync("the vehicle should have at least 1 passenger onboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Train drops off passengers at the correct destination")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Train drops off passengers at the correct destination")]
        public async global::System.Threading.Tasks.Task TrainDropsOffPassengersAtTheCorrectDestination()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Train drops off passengers at the correct destination", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 26
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 24 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
        await testRunner.AndAsync("a level with a Triangle station at (1,0) with a spawn delay of 0 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
        await testRunner.AndAsync("the player will create a line connecting stations at (0,0) and (1,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
        await testRunner.AndAsync("the player will then add a vehicle to the created line at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
        await testRunner.WhenAsync("the simulation runs for 48 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
        await testRunner.ThenAsync("the total score should be at least 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 33
        await testRunner.AndAsync("the Circle station at (0,0) should have fewer than 20 passengers", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Train does not pick up passengers it cannot deliver")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Train does not pick up passengers it cannot deliver")]
        public async global::System.Threading.Tasks.Task TrainDoesNotPickUpPassengersItCannotDeliver()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Train does not pick up passengers it cannot deliver", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 35
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 36
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 24 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 37
        await testRunner.AndAsync("a level with a Triangle station at (1,0) with a spawn delay of 0 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
        await testRunner.AndAsync("a level with a Diamond station at (9,9) with a spawn delay of 0 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
        await testRunner.AndAsync("the player will create a line connecting stations at (0,0) and (1,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
        await testRunner.AndAsync("the player will then add a vehicle to the created line at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
        await testRunner.WhenAsync("the simulation runs for 48 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
        await testRunner.ThenAsync("passengers with Diamond destination should still be at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Train capacity limits the number of passengers picked up")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Train capacity limits the number of passengers picked up")]
        public async global::System.Threading.Tasks.Task TrainCapacityLimitsTheNumberOfPassengersPickedUp()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Train capacity limits the number of passengers picked up", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 46
        await testRunner.GivenAsync("a level with vehicle capacity 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 47
        await testRunner.AndAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 6 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
        await testRunner.AndAsync("a level with a Triangle station at (1,0) with a spawn delay of 0 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
        await testRunner.AndAsync("the player will create a line connecting stations at (0,0) and (1,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
        await testRunner.AndAsync("the player will then add a vehicle to the created line at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
        await testRunner.WhenAsync("the simulation runs for 48 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
        await testRunner.ThenAsync("the vehicle should never have more than 1 passenger onboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Wagon capacity increases the number of passengers a train can carry")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Wagon capacity increases the number of passengers a train can carry")]
        public async global::System.Threading.Tasks.Task WagonCapacityIncreasesTheNumberOfPassengersATrainCanCarry()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Wagon capacity increases the number of passengers a train can carry", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 55
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 56
        await testRunner.GivenAsync("a level with vehicle capacity 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 57
        await testRunner.AndAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 6 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
        await testRunner.AndAsync("a level with a Triangle station at (1,0) with a spawn delay of 0 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Wagon", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
        await testRunner.AndAsync("the player will create a line connecting stations at (0,0) and (1,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
        await testRunner.AndAsync("the player will then add a vehicle to the created line at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
        await testRunner.AndAsync("the player will then add a wagon to the train", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
        await testRunner.WhenAsync("the simulation runs for 48 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
        await testRunner.ThenAsync("the vehicle should never have more than 2 passengers onboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Each passenger pickup and dropoff takes one hour of dwell time")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Each passenger pickup and dropoff takes one hour of dwell time")]
        public async global::System.Threading.Tasks.Task EachPassengerPickupAndDropoffTakesOneHourOfDwellTime()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Each passenger pickup and dropoff takes one hour of dwell time", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 66
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 67
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 6 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 68
        await testRunner.AndAsync("a level with a Triangle station at (1,0) with a spawn delay of 0 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
        await testRunner.AndAsync("the player will create a line connecting stations at (0,0) and (1,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
        await testRunner.AndAsync("the player will then add a vehicle to the created line at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
        await testRunner.WhenAsync("the simulation runs for 48 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
        await testRunner.ThenAsync("the vehicle should have experienced dwell time", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Two trains on the same line both deliver passengers")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Two trains on the same line both deliver passengers")]
        public async global::System.Threading.Tasks.Task TwoTrainsOnTheSameLineBothDeliverPassengers()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Two trains on the same line both deliver passengers", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 75
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 76
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 6 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 77
        await testRunner.AndAsync("a level with a Triangle station at (2,0) with a spawn delay of 0 days and passeng" +
                        "ers every 6 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Train", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
        await testRunner.AndAsync("the player will create a line connecting stations at (0,0) and (2,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
        await testRunner.AndAsync("the player will then add a vehicle to the created line at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
        await testRunner.AndAsync("the player will then add a second vehicle to the created line at station (2,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
        await testRunner.WhenAsync("the simulation runs for 72 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 83
        await testRunner.ThenAsync("the total score should be greater than 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 84
        await testRunner.AndAsync("the snapshot should have 2 active vehicles", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Train with two wagons has triple capacity")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Train with two wagons has triple capacity")]
        public async global::System.Threading.Tasks.Task TrainWithTwoWagonsHasTripleCapacity()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Train with two wagons has triple capacity", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 86
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 87
        await testRunner.GivenAsync("a level with vehicle capacity 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 88
        await testRunner.AndAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 2 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
        await testRunner.AndAsync("a level with a Triangle station at (1,0) with a spawn delay of 0 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Wagon", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
        await testRunner.AndAsync("a weekly gift override for week 2 with resource type Wagon", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
        await testRunner.AndAsync("the player will create a line connecting stations at (0,0) and (1,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 93
        await testRunner.AndAsync("the player will then add a vehicle to the created line at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 94
        await testRunner.AndAsync("the player will then add first wagon to the train", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 95
        await testRunner.AndAsync("the player will then add second wagon to the train", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 96
        await testRunner.WhenAsync("the simulation runs for 100 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 97
        await testRunner.ThenAsync("the vehicle should never have more than 3 passengers onboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 98
        await testRunner.AndAsync("the total score should be greater than 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Train drops off multiple passengers at the same station")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Train drops off multiple passengers at the same station")]
        public async global::System.Threading.Tasks.Task TrainDropsOffMultiplePassengersAtTheSameStation()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Train drops off multiple passengers at the same station", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 100
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 101
        await testRunner.GivenAsync("a level with vehicle capacity 6", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 102
        await testRunner.AndAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 1 hour", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 103
        await testRunner.AndAsync("a level with a Triangle station at (1,0) with a spawn delay of 0 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 105
        await testRunner.AndAsync("the player will create a line connecting stations at (0,0) and (1,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
        await testRunner.AndAsync("the player will then add a vehicle to the created line at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 107
        await testRunner.WhenAsync("the simulation runs for 48 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 108
        await testRunner.ThenAsync("the total score should be at least 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Passengers accumulate when no line is connected")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Passengers accumulate when no line is connected")]
        public async global::System.Threading.Tasks.Task PassengersAccumulateWhenNoLineIsConnected()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Passengers accumulate when no line is connected", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 110
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 111
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 1 hour", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 112
        await testRunner.AndAsync("a level with a Triangle station at (1,0) with a spawn delay of 0 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 113
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
        await testRunner.WhenAsync("the simulation runs for 10 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 115
        await testRunner.ThenAsync("the total score should be 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 116
        await testRunner.AndAsync("the station at (0,0) should have at least 5 passengers", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Score does not increase without delivering to correct type")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Score does not increase without delivering to correct type")]
        public async global::System.Threading.Tasks.Task ScoreDoesNotIncreaseWithoutDeliveringToCorrectType()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Score does not increase without delivering to correct type", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 118
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 119
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 6 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 120
        await testRunner.AndAsync("a level with a Triangle station at (1,0) with a spawn delay of 0 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 121
        await testRunner.AndAsync("a level with a Diamond station at (9,9) with a spawn delay of 0 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 122
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
        await testRunner.AndAsync("the player will create a line connecting stations at (0,0) and (1,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
        await testRunner.AndAsync("the player will then add a vehicle to the created line at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
        await testRunner.WhenAsync("the simulation runs for 48 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 126
        await testRunner.ThenAsync("no vehicle should carry a Diamond passenger", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Train picks up passengers from both directions during ping-pong")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Train picks up passengers from both directions during ping-pong")]
        public async global::System.Threading.Tasks.Task TrainPicksUpPassengersFromBothDirectionsDuringPing_Pong()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Train picks up passengers from both directions during ping-pong", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 128
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 129
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 6 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 130
        await testRunner.AndAsync("a level with a Triangle station at (1,0) with a spawn delay of 0 days and passeng" +
                        "ers every 6 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 131
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 132
        await testRunner.AndAsync("the player will create a line connecting stations at (0,0) and (1,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 133
        await testRunner.AndAsync("the player will then add a vehicle to the created line at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 134
        await testRunner.WhenAsync("the simulation runs for 72 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 135
        await testRunner.ThenAsync("the total score should be at least 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Multiple trains on a three-station line deliver efficiently")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Multiple trains on a three-station line deliver efficiently")]
        public async global::System.Threading.Tasks.Task MultipleTrainsOnAThree_StationLineDeliverEfficiently()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Multiple trains on a three-station line deliver efficiently", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 137
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 138
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 4 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 139
        await testRunner.AndAsync("a level with a Triangle station at (1,0) with a spawn delay of 0 days and passeng" +
                        "ers every 4 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 140
        await testRunner.AndAsync("a level with a Diamond station at (2,0) with a spawn delay of 0 days and passenge" +
                        "rs every 4 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 141
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Train", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 142
        await testRunner.AndAsync("the player will create a line connecting stations at (0,0) and (1,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 143
        await testRunner.AndAsync("the player will then extend the created line from station (1,0) to station (2,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 144
        await testRunner.AndAsync("the player will then add a vehicle to the created line at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 145
        await testRunner.AndAsync("the player will then add a second vehicle to the created line at station (2,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 146
        await testRunner.WhenAsync("the simulation runs for 120 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 147
        await testRunner.ThenAsync("the total score should be at least 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Removing a vehicle while carrying passengers loses them")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Removing a vehicle while carrying passengers loses them")]
        public async global::System.Threading.Tasks.Task RemovingAVehicleWhileCarryingPassengersLosesThem()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Removing a vehicle while carrying passengers loses them", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 149
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 150
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 1 hour", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 151
        await testRunner.AndAsync("a level with a Triangle station at (3,0) with a spawn delay of 0 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 152
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 153
        await testRunner.AndAsync("the player will create a line connecting stations at (0,0) and (3,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 154
        await testRunner.AndAsync("the player will then add a vehicle to the created line at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 155
        await testRunner.AndAsync("the player will then remove the added vehicle", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 156
        await testRunner.WhenAsync("the simulation runs for 24 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 157
        await testRunner.ThenAsync("the snapshot should have 0 active vehicles", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 158
        await testRunner.AndAsync("the snapshot should have 1 available vehicle", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Train does not exceed capacity even with many passengers waiting")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Train does not exceed capacity even with many passengers waiting")]
        public async global::System.Threading.Tasks.Task TrainDoesNotExceedCapacityEvenWithManyPassengersWaiting()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Train does not exceed capacity even with many passengers waiting", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 160
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 161
        await testRunner.GivenAsync("a level with vehicle capacity 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 162
        await testRunner.AndAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 1 hour", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 163
        await testRunner.AndAsync("a level with a Triangle station at (5,0) with a spawn delay of 0 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 164
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 165
        await testRunner.AndAsync("the player will create a line connecting stations at (0,0) and (5,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 166
        await testRunner.AndAsync("the player will then add a vehicle to the created line at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 167
        await testRunner.WhenAsync("the simulation runs for 48 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 168
        await testRunner.ThenAsync("the vehicle should never have more than 2 passengers onboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Passengers at disconnected station are not picked up by trains on other lines")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Passengers at disconnected station are not picked up by trains on other lines")]
        public async global::System.Threading.Tasks.Task PassengersAtDisconnectedStationAreNotPickedUpByTrainsOnOtherLines()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Passengers at disconnected station are not picked up by trains on other lines", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 170
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 171
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 6 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 172
        await testRunner.AndAsync("a level with a Triangle station at (1,0) with a spawn delay of 0 days and passeng" +
                        "ers every 6 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 173
        await testRunner.AndAsync("a level with a Diamond station at (9,9) with a spawn delay of 0 days and passenge" +
                        "rs every 6 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 174
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 175
        await testRunner.AndAsync("the player will create a line connecting stations at (0,0) and (1,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 176
        await testRunner.AndAsync("the player will then add a vehicle to the created line at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 177
        await testRunner.WhenAsync("the simulation runs for 48 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 178
        await testRunner.ThenAsync("the station at (9,9) should have at least 1 passengers", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Active train prevents game over by picking up passengers")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Pickup and Delivery")]
        [global::Xunit.TraitAttribute("Description", "Active train prevents game over by picking up passengers")]
        public async global::System.Threading.Tasks.Task ActiveTrainPreventsGameOverByPickingUpPassengers()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Active train prevents game over by picking up passengers", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 180
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 181
        await testRunner.GivenAsync("a level with vehicle capacity 6", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 182
        await testRunner.AndAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 4 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 183
        await testRunner.AndAsync("a level with a Triangle station at (1,0) with a spawn delay of 0 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 184
        await testRunner.AndAsync("a weekly gift override for week 1 with resource type Line", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 185
        await testRunner.AndAsync("the player will create a line connecting stations at (0,0) and (1,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 186
        await testRunner.AndAsync("the player will then add a vehicle to the created line at station (0,0)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 187
        await testRunner.WhenAsync("the simulation runs for 100 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 188
        await testRunner.ThenAsync("\"OnGameOver\" should have fired exactly 0 times", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 189
        await testRunner.AndAsync("the total score should be greater than 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await PassengerPickupAndDeliveryFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await PassengerPickupAndDeliveryFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
