// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace MetroMania.Engine.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PassengerSpawningFeature : object, global::Xunit.IClassFixture<PassengerSpawningFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Passenger Spawning", @"    Passengers spawn at metro stations based on each station's PassengerSpawnPhases.
    Each phase defines a day threshold (AfterDays) and a spawn frequency (FrequencyInHours).
    The active phase is the one with the highest AfterDays that the station has reached.
    Stations without spawn phases never spawn passengers. When no passengers can spawn
    and no game-over occurs, the simulation runs indefinitely and must be cancelled
    via a CancellationToken.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PassengerSpawning.feature"
#line hidden
        
        public PassengerSpawningFeature(PassengerSpawningFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/PassengerSpawning.feature.ndjson", 8);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Single station with one spawn phase spawns passengers at the correct frequency")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Spawning")]
        [global::Xunit.TraitAttribute("Description", "Single station with one spawn phase spawns passengers at the correct frequency")]
        public async global::System.Threading.Tasks.Task SingleStationWithOneSpawnPhaseSpawnsPassengersAtTheCorrectFrequency()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Single station with one spawn phase spawns passengers at the correct frequency", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 9
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 12 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 11
        await testRunner.WhenAsync("the simulation runs for 49 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
        await testRunner.ThenAsync("\"OnPassengerWaiting\" should have fired exactly 4 times", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Day",
                            "Hour",
                            "X",
                            "Y",
                            "PassengerCount"});
                table1.AddRow(new string[] {
                            "1",
                            "12",
                            "0",
                            "0",
                            "1"});
                table1.AddRow(new string[] {
                            "2",
                            "0",
                            "0",
                            "0",
                            "2"});
                table1.AddRow(new string[] {
                            "2",
                            "12",
                            "0",
                            "0",
                            "3"});
                table1.AddRow(new string[] {
                            "3",
                            "0",
                            "0",
                            "0",
                            "4"});
#line 13
        await testRunner.AndAsync("the passenger waiting events should be:", ((string)(null)), table1, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Station without spawn phases never spawns passengers and simulation is cancelled")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Spawning")]
        [global::Xunit.TraitAttribute("Description", "Station without spawn phases never spawns passengers and simulation is cancelled")]
        public async global::System.Threading.Tasks.Task StationWithoutSpawnPhasesNeverSpawnsPassengersAndSimulationIsCancelled()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Station without spawn phases never spawns passengers and simulation is cancelled", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 20
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and no passen" +
                        "ger spawn phases", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
        await testRunner.AndAsync("the simulation will be cancelled after 200 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
        await testRunner.WhenAsync("the simulation runs until game over or cancellation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
        await testRunner.ThenAsync("the simulation should have been cancelled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 25
        await testRunner.AndAsync("\"OnPassengerWaiting\" should have fired exactly 0 times", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Station with multiple spawn phases transitions to faster frequency")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Spawning")]
        [global::Xunit.TraitAttribute("Description", "Station with multiple spawn phases transitions to faster frequency")]
        public async global::System.Threading.Tasks.Task StationWithMultipleSpawnPhasesTransitionsToFasterFrequency()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Station with multiple spawn phases transitions to faster frequency", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "AfterDays",
                            "FrequencyInHours"});
                table2.AddRow(new string[] {
                            "0",
                            "24"});
                table2.AddRow(new string[] {
                            "2",
                            "12"});
#line 28
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and the follo" +
                        "wing spawn phases:", ((string)(null)), table2, "Given ");
#line hidden
#line 32
        await testRunner.WhenAsync("the simulation runs for 73 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
        await testRunner.ThenAsync("\"OnPassengerWaiting\" should have fired exactly 4 times", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Day",
                            "Hour",
                            "X",
                            "Y",
                            "PassengerCount"});
                table3.AddRow(new string[] {
                            "2",
                            "0",
                            "0",
                            "0",
                            "1"});
                table3.AddRow(new string[] {
                            "3",
                            "0",
                            "0",
                            "0",
                            "2"});
                table3.AddRow(new string[] {
                            "3",
                            "12",
                            "0",
                            "0",
                            "3"});
                table3.AddRow(new string[] {
                            "4",
                            "0",
                            "0",
                            "0",
                            "4"});
#line 34
        await testRunner.AndAsync("the passenger waiting events should be:", ((string)(null)), table3, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Multiple stations with different spawn phases fire events in correct order")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Spawning")]
        [global::Xunit.TraitAttribute("Description", "Multiple stations with different spawn phases fire events in correct order")]
        public async global::System.Threading.Tasks.Task MultipleStationsWithDifferentSpawnPhasesFireEventsInCorrectOrder()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Multiple stations with different spawn phases fire events in correct order", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 41
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "AfterDays",
                            "FrequencyInHours"});
                table4.AddRow(new string[] {
                            "0",
                            "24"});
                table4.AddRow(new string[] {
                            "3",
                            "12"});
#line 42
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and the follo" +
                        "wing spawn phases:", ((string)(null)), table4, "Given ");
#line hidden
#line 46
        await testRunner.AndAsync("a level with a Triangle station at (1,0) with a spawn delay of 1 day and passenge" +
                        "rs every 24 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
        await testRunner.WhenAsync("the simulation runs for 97 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
        await testRunner.ThenAsync("\"OnPassengerWaiting\" should have fired exactly 8 times", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Day",
                            "Hour",
                            "X",
                            "Y",
                            "PassengerCount"});
                table5.AddRow(new string[] {
                            "2",
                            "0",
                            "0",
                            "0",
                            "1"});
                table5.AddRow(new string[] {
                            "3",
                            "0",
                            "0",
                            "0",
                            "2"});
                table5.AddRow(new string[] {
                            "3",
                            "0",
                            "1",
                            "0",
                            "1"});
                table5.AddRow(new string[] {
                            "4",
                            "0",
                            "0",
                            "0",
                            "3"});
                table5.AddRow(new string[] {
                            "4",
                            "0",
                            "1",
                            "0",
                            "2"});
                table5.AddRow(new string[] {
                            "4",
                            "12",
                            "0",
                            "0",
                            "4"});
                table5.AddRow(new string[] {
                            "5",
                            "0",
                            "0",
                            "0",
                            "5"});
                table5.AddRow(new string[] {
                            "5",
                            "0",
                            "1",
                            "0",
                            "3"});
#line 49
        await testRunner.AndAsync("the passenger waiting events should be:", ((string)(null)), table5, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Passenger destination type always differs from origin station type")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Spawning")]
        [global::Xunit.TraitAttribute("Description", "Passenger destination type always differs from origin station type")]
        public async global::System.Threading.Tasks.Task PassengerDestinationTypeAlwaysDiffersFromOriginStationType()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Passenger destination type always differs from origin station type", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 60
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 61
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 0 days and passenger" +
                        "s every 1 hour", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
        await testRunner.WhenAsync("the simulation runs for 11 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
        await testRunner.ThenAsync("all passengers should have a destination type different from their origin station" +
                        " type", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Station with spawn delay and immediate phase spawns passengers after delay")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Passenger Spawning")]
        [global::Xunit.TraitAttribute("Description", "Station with spawn delay and immediate phase spawns passengers after delay")]
        public async global::System.Threading.Tasks.Task StationWithSpawnDelayAndImmediatePhaseSpawnsPassengersAfterDelay()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Station with spawn delay and immediate phase spawns passengers after delay", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 65
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 66
        await testRunner.GivenAsync("a level with a Circle station at (0,0) with a spawn delay of 2 days and passenger" +
                        "s every 24 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 67
        await testRunner.WhenAsync("the simulation runs for 97 hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 68
        await testRunner.ThenAsync("\"OnPassengerWaiting\" should have fired exactly 2 times", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Day",
                            "Hour",
                            "X",
                            "Y",
                            "PassengerCount"});
                table6.AddRow(new string[] {
                            "4",
                            "0",
                            "0",
                            "0",
                            "1"});
                table6.AddRow(new string[] {
                            "5",
                            "0",
                            "0",
                            "0",
                            "2"});
#line 69
        await testRunner.AndAsync("the passenger waiting events should be:", ((string)(null)), table6, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await PassengerSpawningFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await PassengerSpawningFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
