using MetroMania.Domain.Entities;
using MetroMania.Domain.Enums;

namespace MetroMania.Demo.Levels;

internal static class BonusLevel
{
    public static Level Level => new Level
    {
        Id = Guid.NewGuid(),
        Title = "Bonus Level",
        Description = "The ultimate mega level of chaos",
        GridWidth = 30,
        GridHeight = 20,
        LevelData = new LevelData
        {
            BackgroundColor = "#A8A49D",
            WaterColor = "#BDEC99",
            Seed = 974427613,
            VehicleCapacity = 8,
            MaxDays = 365,
            LocalizedContent = new()
            {
                ["en"] = new LocalizedLevelText { Title = "Bonus Level", Description = "The ultimate mega level of chaos" },
                ["nl"] = new LocalizedLevelText { Title = "Bonuslevel", Description = "Het ultieme meganiveau van chaos" },
                ["ar"] = new LocalizedLevelText { Title = "مرحلة إضافية", Description = "المرحلة الضخمة النهائية للفوضى" },
            },
            InitialResources = [ResourceType.Line, ResourceType.Train],
            Stations =
            [
                new MetroStation { GridX = 12, GridY = 10, StationType = StationType.Circle,    SpawnDelayDays = 0,  PassengerSpawnPhases = [new() { AfterDays = 0, FrequencyInHours = 12 }] },
                new MetroStation { GridX = 25, GridY = 8,  StationType = StationType.Triangle,  SpawnDelayDays = 0,  PassengerSpawnPhases = [new() { AfterDays = 0, FrequencyInHours = 12 }] },
                new MetroStation { GridX = 3,  GridY = 2,  StationType = StationType.Rectangle, SpawnDelayDays = 4,  PassengerSpawnPhases = [new() { AfterDays = 0, FrequencyInHours = 12 }] },
                new MetroStation { GridX = 21, GridY = 11, StationType = StationType.Diamond,   SpawnDelayDays = 8,  PassengerSpawnPhases = [new() { AfterDays = 0, FrequencyInHours = 12 }] },
                new MetroStation { GridX = 9,  GridY = 4,  StationType = StationType.Triangle,  SpawnDelayDays = 12, PassengerSpawnPhases = [new() { AfterDays = 6, FrequencyInHours = 12 }] },
                new MetroStation { GridX = 27, GridY = 18, StationType = StationType.Rectangle, SpawnDelayDays = 16, PassengerSpawnPhases = [new() { AfterDays = 0, FrequencyInHours = 12 }] },
                new MetroStation { GridX = 28, GridY = 1,  StationType = StationType.Circle,    SpawnDelayDays = 20, PassengerSpawnPhases = [new() { AfterDays = 0, FrequencyInHours = 12 }] },
                new MetroStation { GridX = 28, GridY = 12, StationType = StationType.Circle,    SpawnDelayDays = 24, PassengerSpawnPhases = [new() { AfterDays = 0, FrequencyInHours = 12 }] },
                new MetroStation { GridX = 5,  GridY = 7,  StationType = StationType.Circle,    SpawnDelayDays = 28, PassengerSpawnPhases = [new() { AfterDays = 0, FrequencyInHours = 12 }] },
                new MetroStation { GridX = 3,  GridY = 18, StationType = StationType.Star,      SpawnDelayDays = 32, PassengerSpawnPhases = [new() { AfterDays = 0, FrequencyInHours = 12 }] },
                new MetroStation { GridX = 14, GridY = 17, StationType = StationType.Triangle,  SpawnDelayDays = 36, PassengerSpawnPhases = [new() { AfterDays = 0, FrequencyInHours = 12 }] },
                new MetroStation { GridX = 17, GridY = 2,  StationType = StationType.Pentagon,  SpawnDelayDays = 40, PassengerSpawnPhases = [new() { AfterDays = 0, FrequencyInHours = 12 }] },
            ],
            WaterTiles =
            [
                new Water { GridX = 0,  GridY = 14 }, new Water { GridX = 1,  GridY = 14 }, new Water { GridX = 2,  GridY = 14 },
                new Water { GridX = 3,  GridY = 13 }, new Water { GridX = 3,  GridY = 14 }, new Water { GridX = 0,  GridY = 15 },
                new Water { GridX = 1,  GridY = 15 }, new Water { GridX = 2,  GridY = 15 }, new Water { GridX = 4,  GridY = 14 },
                new Water { GridX = 2,  GridY = 13 }, new Water { GridX = 4,  GridY = 13 }, new Water { GridX = 5,  GridY = 14 },
                new Water { GridX = 6,  GridY = 14 }, new Water { GridX = 5,  GridY = 13 }, new Water { GridX = 6,  GridY = 13 },
                new Water { GridX = 7,  GridY = 13 }, new Water { GridX = 7,  GridY = 14 }, new Water { GridX = 8,  GridY = 14 },
                new Water { GridX = 8,  GridY = 13 }, new Water { GridX = 9,  GridY = 13 }, new Water { GridX = 9,  GridY = 14 },
                new Water { GridX = 9,  GridY = 15 }, new Water { GridX = 10, GridY = 15 }, new Water { GridX = 10, GridY = 14 },
                new Water { GridX = 10, GridY = 13 }, new Water { GridX = 11, GridY = 14 }, new Water { GridX = 11, GridY = 15 },
                new Water { GridX = 3,  GridY = 15 }, new Water { GridX = 12, GridY = 15 }, new Water { GridX = 12, GridY = 14 },
                new Water { GridX = 12, GridY = 16 }, new Water { GridX = 13, GridY = 16 }, new Water { GridX = 14, GridY = 16 },
                new Water { GridX = 15, GridY = 16 }, new Water { GridX = 13, GridY = 15 }, new Water { GridX = 15, GridY = 15 },
                new Water { GridX = 14, GridY = 15 }, new Water { GridX = 11, GridY = 16 }, new Water { GridX = 16, GridY = 16 },
                new Water { GridX = 16, GridY = 15 }, new Water { GridX = 17, GridY = 15 }, new Water { GridX = 17, GridY = 16 },
                new Water { GridX = 19, GridY = 16 }, new Water { GridX = 18, GridY = 16 }, new Water { GridX = 18, GridY = 15 },
                new Water { GridX = 19, GridY = 15 }, new Water { GridX = 20, GridY = 16 }, new Water { GridX = 20, GridY = 17 },
                new Water { GridX = 21, GridY = 17 }, new Water { GridX = 21, GridY = 16 }, new Water { GridX = 20, GridY = 15 },
                new Water { GridX = 21, GridY = 15 }, new Water { GridX = 22, GridY = 16 }, new Water { GridX = 22, GridY = 17 },
                new Water { GridX = 23, GridY = 17 }, new Water { GridX = 24, GridY = 17 }, new Water { GridX = 26, GridY = 17 },
                new Water { GridX = 25, GridY = 17 }, new Water { GridX = 27, GridY = 17 }, new Water { GridX = 28, GridY = 17 },
                new Water { GridX = 29, GridY = 17 }, new Water { GridX = 29, GridY = 16 }, new Water { GridX = 28, GridY = 16 },
                new Water { GridX = 27, GridY = 16 }, new Water { GridX = 26, GridY = 16 }, new Water { GridX = 25, GridY = 16 },
                new Water { GridX = 24, GridY = 16 }, new Water { GridX = 23, GridY = 16 }, new Water { GridX = 18, GridY = 14 },
                new Water { GridX = 18, GridY = 13 }, new Water { GridX = 18, GridY = 12 }, new Water { GridX = 18, GridY = 11 },
                new Water { GridX = 18, GridY = 10 }, new Water { GridX = 18, GridY = 9  }, new Water { GridX = 19, GridY = 8  },
                new Water { GridX = 18, GridY = 8  }, new Water { GridX = 20, GridY = 8  }, new Water { GridX = 21, GridY = 8  },
                new Water { GridX = 22, GridY = 8  }, new Water { GridX = 22, GridY = 7  }, new Water { GridX = 22, GridY = 9  },
                new Water { GridX = 23, GridY = 9  }, new Water { GridX = 23, GridY = 8  }, new Water { GridX = 23, GridY = 7  },
                new Water { GridX = 23, GridY = 6  }, new Water { GridX = 24, GridY = 6  }, new Water { GridX = 23, GridY = 10 },
                new Water { GridX = 24, GridY = 10 }, new Water { GridX = 24, GridY = 9  }, new Water { GridX = 24, GridY = 8  },
                new Water { GridX = 24, GridY = 7  }, new Water { GridX = 25, GridY = 6  }, new Water { GridX = 25, GridY = 7  },
                new Water { GridX = 26, GridY = 7  }, new Water { GridX = 26, GridY = 8  }, new Water { GridX = 26, GridY = 9  },
                new Water { GridX = 25, GridY = 9  }, new Water { GridX = 25, GridY = 10 }, new Water { GridX = 26, GridY = 10 },
                new Water { GridX = 27, GridY = 10 }, new Water { GridX = 27, GridY = 9  }, new Water { GridX = 27, GridY = 8  },
                new Water { GridX = 27, GridY = 7  }, new Water { GridX = 27, GridY = 6  }, new Water { GridX = 26, GridY = 6  },
                new Water { GridX = 28, GridY = 8  }, new Water { GridX = 29, GridY = 8  }, new Water { GridX = 28, GridY = 7  },
                new Water { GridX = 28, GridY = 9  }, new Water { GridX = 0,  GridY = 0  }, new Water { GridX = 0,  GridY = 1  },
                new Water { GridX = 0,  GridY = 2  }, new Water { GridX = 1,  GridY = 2  }, new Water { GridX = 1,  GridY = 1  },
                new Water { GridX = 1,  GridY = 0  }, new Water { GridX = 2,  GridY = 0  }, new Water { GridX = 2,  GridY = 1  },
                new Water { GridX = 2,  GridY = 2  }, new Water { GridX = 3,  GridY = 0  }, new Water { GridX = 0,  GridY = 3  },
                new Water { GridX = 4,  GridY = 0  }, new Water { GridX = 0,  GridY = 4  }, new Water { GridX = 1,  GridY = 3  },
                new Water { GridX = 3,  GridY = 1  }, new Water { GridX = 5,  GridY = 0  }, new Water { GridX = 0,  GridY = 5  },
            ],
            WeeklyGiftOverrides =
            [
                new WeeklyGiftOverride { Week = 2,  ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 3,  ResourceType = ResourceType.Line  },
                new WeeklyGiftOverride { Week = 4,  ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 5,  ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 6,  ResourceType = ResourceType.Line  },
                new WeeklyGiftOverride { Week = 7,  ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 8,  ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 9,  ResourceType = ResourceType.Line  },
                new WeeklyGiftOverride { Week = 10, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 11, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 12, ResourceType = ResourceType.Line  },
                new WeeklyGiftOverride { Week = 13, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 14, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 15, ResourceType = ResourceType.Line  },
                new WeeklyGiftOverride { Week = 16, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 17, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 18, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 19, ResourceType = ResourceType.Line  },
                new WeeklyGiftOverride { Week = 20, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 21, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 22, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 23, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 24, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 25, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 26, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 27, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 28, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 29, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 30, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 31, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 32, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 33, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 34, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 35, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 36, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 37, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 38, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 39, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 40, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 41, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 42, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 43, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 44, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 45, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 46, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 47, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 48, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 49, ResourceType = ResourceType.Train },
                new WeeklyGiftOverride { Week = 50, ResourceType = ResourceType.Train },
            ],
        }
    };
}
